import Head from "next/head";
import Postcard from "../components/Cards/PostCard";
import Link from "next/link";
import posts from "../data/postsData.js";
import Section from "../components/Sections/Section";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* body */}
      {/* section 1 */}
      <Section>
        <div className="flex items-center  flex-wrap ">
          <h1 className="w-full p-5 font-bold"> Section Title </h1>
          {posts.map((e, i) => (
            <Link href={`posts/${e.id}`} key={i}>
              <a>
                <Postcard body={e.body} user={e.user} banner={e.image} />
              </a>
            </Link>
          ))}
        </div>
      </Section>
      
      <Section>
            
      </Section>
    </div>
  );
}
